version: "3"
services:
  app:
    container_name: school_server
    build: .
    command: python serve.py -log_file_prefix=logs/server.log
    environment:
      - REDIS_HOST=redis
    ports:
      - "55552:8888"
    volumes:
      - .:/home
      - ./logs:/home/logs
    depends_on:
      - redis
      
  redis:
    image: redis:alpine
